# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3d3775c0662ca5fe530d7cbe4d15d20495213648c182ad315b9614743b30b8bb28944238af899a42e6355d951207417776380f7aee94e8c4dae57ab3cbe20db

test:
  secret_key_base: 9b0369f6d9166e88709b6e73336754683ca155b080914a3d9cee239186aeb4be88c064fce516509675bae1f94de2c58f9927761bffaf31ce6aa7d2e96f38c090

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
