require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AgreementsController do

  # This to return the minimal set of attributes required to create a valid
  # Agreement. As you add validations to Agreement, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { :name => "Agreement name"}
  end
  
  before (:each) do
    @user = FactoryGirl.create(:user)
    sign_in @user
  end

  describe "GET index" do
    it "assigns all agreements as @agreements" do
      agreement = Agreement.create! valid_attributes
      get :index
      expect(assigns(:agreements)).to eq([agreement])
    end
  end

  describe "GET show" do
    it "assigns the requested agreement as @agreement" do
      agreement = Agreement.create! valid_attributes
      get :show, :id => agreement.id.to_s
      expect(assigns(:agreement)).to eq(agreement)
    end
  end

  describe "GET new" do
    it "assigns a new agreement as @agreement" do
      get :new
      expect(assigns(:agreement)).to be_a_new(Agreement)
    end
  end

  describe "GET edit" do
    it "assigns the requested agreement as @agreement" do
      agreement = Agreement.create! valid_attributes
      get :edit, :id => agreement.id.to_s
      expect(assigns(:agreement)).to eq(agreement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Agreement" do
        expect {
          post :create, :agreement => valid_attributes
        }.to change(Agreement, :count).by(1)
      end

      it "assigns a newly created agreement as @agreement" do
        post :create, :agreement => valid_attributes
        expect(assigns(:agreement)).to be_a(Agreement)
        expect(assigns(:agreement)).to be_persisted
      end

      it "redirects to the created agreement" do
        post :create, :agreement => valid_attributes
        expect(response).to redirect_to(Agreement.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved agreement as @agreement" do
        # Trigger the behavior that occurs when invalid params are submitted
        post :create, :agreement => { :name => "" }
        expect(assigns(:agreement)).to be_a_new(Agreement)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        post :create, :agreement => { :name => "" }
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested agreement" do
        agreement = Agreement.create! valid_attributes
        put :update, :id => agreement.id, :agreement => { name: "New name" }
        agreement.reload
        expect(agreement).to have_attributes(:name => "New name")
      end

      it "assigns the requested agreement as @agreement" do
        agreement = Agreement.create! valid_attributes
        put :update, :id => agreement.id, :agreement => { name: "New name" }
        expect(assigns(:agreement)).to eq(agreement)
      end

      it "redirects to the agreement" do
        agreement = Agreement.create! valid_attributes
        put :update, :id => agreement.id, :agreement => { name: "New name" }
        expect(response).to redirect_to(agreement)
      end
    end

    describe "with invalid params" do
      it "assigns the agreement as @agreement" do
        agreement = Agreement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Agreement.any_instance.stub(:save).and_return(false)
        put :update, :id => agreement.id.to_s, :agreement => { :name => "" }
        expect(assigns(:agreement)).to eq(agreement)
      end

      it "re-renders the 'edit' template" do
        agreement = Agreement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Agreement.any_instance.stub(:save).and_return(false)
        put :update, :id => agreement.id.to_s, :agreement => { :name => "" }
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested agreement" do
      agreement = Agreement.create! valid_attributes
      expect {
        delete :destroy, :id => agreement.id.to_s
      }.to change(Agreement, :count).by(-1)
    end

    it "redirects to the agreements list" do
      agreement = Agreement.create! valid_attributes
      delete :destroy, :id => agreement.id.to_s
      expect(response).to redirect_to(agreements_url)
    end
  end

end
